### ISSUE TITLE
数据集下载不了

### ISSUE THREAD

**Issue by laiqirong** [onlyzdd/deep-ecg#6]
请问这个数据集是原始心电数据吗

**Comment by onlyzdd** [comment]
你可以从 [CPSC2018](http://2018.icbeb.org/Challenge.html)、[Physionet 2020 Challenge](https://physionet.org/content/challenge-2020/1.0.1/) 或者[这里](https://www.dropbox.com/s/unicm8ulxt24vh8/CPSC.zip?dl=0)下载数据集。Dropbox 上的文件是原始数据，只是组织上更规整一些。

**Comment by rdyan0053** [comment]
Hello, I have downloaded the CPSC2018 dataset. But I found that the dataset and the code `preprocess.py` do not match.

For example, in the CPSC2018 dataset, here are 3 folders `TrainingSet1`, `TrainingSet2`, `TrainingSet3`. And in these folders, here only mat files, no hea files. But in the `preprocess.py`, the line `recordpaths = glob(os.path.join(data_dir, '*.hea'))` is to find all paths of hea file.

So, I have a little confusion.

**Comment by rdyan0053** [comment]
> 

sorry, i have see the dataset in dropbox, thank you

**Comment by onlyzdd** [comment]
> Hello, I have downloaded the CPSC2018 dataset. But I found that the dataset and the code `preprocess.py` do not match.
> 
> For example, in the CPSC2018 dataset, here are 3 folders `TrainingSet1`, `TrainingSet2`, `TrainingSet3`. And in these folders, here only mat files, no hea files. But in the `preprocess.py`, the line `recordpaths = glob(os.path.join(data_dir, '*.hea'))` is to find all paths of hea file.
> 
> So, I have a little confusion.

@rdyan0053 They are exactly the same data but in different formats. New format of the CPSC2018 data is avaliable as part of training data in the PhysioNet 2020 Challange. It's better orangized and can be easily loaded with the `wfdb` package.

If you're not using the Dropbox one, you may need to make some changes on data loading and preprocessing.

**Comment by rdyan0053** [comment]
> > Hello, I have downloaded the CPSC2018 dataset. But I found that the dataset and the code `preprocess.py` do not match.
> > For example, in the CPSC2018 dataset, here are 3 folders `TrainingSet1`, `TrainingSet2`, `TrainingSet3`. And in these folders, here only mat files, no hea files. But in the `preprocess.py`, the line `recordpaths = glob(os.path.join(data_dir, '*.hea'))` is to find all paths of hea file.
> > So, I have a little confusion.
> 
> @rdyan0053 They are exactly the same data but in different formats. New format of the CPSC2018 data is avaliable as part of training data in the PhysioNet 2020 Challange. It's better orangized and can be easily loaded with the `wfdb` package.
> 
> If you're not using the Dropbox one, you may need to make some changes on data loading and preprocessing.

Right. Thank you very much!!!
